<script lang="ts">
  // TASK-BR1 — the opt-in bug report dialog.
  //
  // The rule this whole feature turns on: **nothing sends**. Both submit
  // buttons open a pre-filled draft in something the user already trusts
  // — their GitHub account, their mail client — and stop there. So the
  // dialog's real job is not collecting a description; it is showing the
  // user the exact bytes that would leave the machine, before they leave
  // it. That is what the read-only preview is for, and it comes from the
  // same Rust builder the submit path uses. A preview generated by a
  // second implementation would be a preview of nothing.
  import Modal from "../common/Modal.svelte";
  import { t } from "../../lib/i18n/t";
  import { toastStore } from "../../lib/stores/toast.svelte";
  import * as files from "../../lib/ipc/files";
  import {
    clearCrash,
    context as fetchContext,
    preview as fetchPreview,
    submit as submitReport,
    type BugReportContext
  } from "../../lib/ipc/bugreport";

  interface Props {
    open: boolean;
    onClose: () => void;
  }
  let { open, onClose }: Props = $props();

  let ctx = $state<BugReportContext | null>(null);
  let description = $state("");
  let includeCrash = $state(true);
  let preview = $state("");
  let busy = $state(false);

  /** Long enough that a burst of typing produces one preview, short
   *  enough that a pause feels immediate. */
  const PREVIEW_DEBOUNCE_MS = 200;

  // Load on open rather than on mount: a pending crash is discovered by
  // the Rust side reading the crash directory, and the dialog can be
  // opened again after one has been discarded.
  $effect(() => {
    if (!open) return;
    void (async () => {
      try {
        ctx = await fetchContext();
      } catch (e) {
        console.warn("[bugreport] context failed:", e);
        ctx = null;
      }
    })();
  });

  // Re-render the preview whenever anything that feeds it changes, so
  // what the user reads is never behind what would be sent.
  //
  // Debounced: every call is an IPC round trip that re-reads the crash
  // file, re-scrubs it and ships the whole body back, and without this it
  // fired once per keystroke.
  $effect(() => {
    if (!open) return;
    const body = description;
    const crash = includeCrash && !!ctx?.pendingCrash;
    const timer = setTimeout(() => {
      void (async () => {
        try {
          preview = await fetchPreview(body, crash);
        } catch (e) {
          console.warn("[bugreport] preview failed:", e);
        }
      })();
    }, PREVIEW_DEBOUNCE_MS);
    return () => clearTimeout(timer);
  });

  async function submit(target: "github" | "gmail" | "email") {
    busy = true;
    try {
      const hadCrash = !!ctx?.pendingCrash;
      await submitReport(target, description, includeCrash && hadCrash);
      // The report has been handed over, so stop offering it. Without
      // this the dialog re-opened on every launch forever — and since a
      // pending crash defers the update check, it silently suppressed
      // that as well. `clear_crashes`'s own doc says "sent or dismissed";
      // only the dismissed half had a caller.
      if (hadCrash) {
        try {
          await clearCrash();
          ctx = await fetchContext();
        } catch (e) {
          console.warn("[bugreport] could not clear the crash:", e);
        }
      }
      toastStore.show(t("bugreport-opened"));
      onClose();
    } catch (e) {
      toastStore.error(t("bugreport-failed", { error: String(e) }));
    } finally {
      busy = false;
    }
  }

  async function copyReport() {
    try {
      await files.copyText(preview);
      toastStore.show(t("bugreport-copied"));
    } catch (e) {
      toastStore.error(t("bugreport-failed", { error: String(e) }));
    }
  }

  async function discardCrash() {
    try {
      await clearCrash();
      // Re-read rather than patching the local copy: the crash file is
      // the source of truth and it may not be the only one.
      ctx = await fetchContext();
      includeCrash = false;
    } catch (e) {
      toastStore.error(t("bugreport-failed", { error: String(e) }));
    }
  }
</script>

<Modal
  {open}
  {onClose}
  labelledBy="bugreport-heading"
  dismissOnBackdrop={false}
  style="width: min(720px, 92vw); max-height: 86vh;"
>
  <h2 id="bugreport-heading">{t("bugreport-title")}</h2>

  {#if ctx?.pendingCrash}
    <p class="crash-notice">{t("bugreport-crash-notice")}</p>
  {/if}

  <label class="field" for="bugreport-what">{t("bugreport-what-happened")}</label>
  <textarea
    id="bugreport-what"
    bind:value={description}
    rows="4"
    placeholder={t("bugreport-placeholder")}
  ></textarea>

  {#if ctx?.pendingCrash}
    <label class="check">
      <input type="checkbox" bind:checked={includeCrash} />
      {t("bugreport-include-crash")}
    </label>
  {/if}

  <p class="field">{t("bugreport-exact-text")}</p>
  <!-- Read-only, not disabled: a disabled textarea is unreachable by
       keyboard, and this is the one element a cautious user most wants
       to select and read through. -->
  <textarea class="preview" readonly rows="10" value={preview}></textarea>

  <p class="privacy">{t("bugreport-privacy")}</p>

  <div class="actions">
    <button onclick={() => submit("github")} disabled={busy}>{t("bugreport-github")}</button>
    <button onclick={() => submit("gmail")} disabled={busy}>{t("bugreport-gmail")}</button>
    <button onclick={() => submit("email")} disabled={busy}>{t("bugreport-email")}</button>
    <button onclick={copyReport} disabled={busy}>{t("bugreport-copy")}</button>
    {#if ctx?.pendingCrash}
      <button class="discard" onclick={discardCrash} disabled={busy}>
        {t("bugreport-discard-crash")}
      </button>
    {/if}
  </div>
</Modal>

<style>
  h2 {
    margin: 0 0 12px;
    font-size: 15px;
    color: var(--text-primary);
  }
  .crash-notice {
    margin: 0 0 12px;
    padding: 8px 10px;
    border: 1px solid var(--border);
    border-left: 3px solid var(--accent-orange);
    border-radius: 3px;
    background: var(--bg-canvas);
    color: var(--text-primary);
    font-size: 12px;
  }
  .field {
    display: block;
    margin: 12px 0 4px;
    font-size: 12px;
    color: var(--text-secondary);
  }
  textarea {
    width: 100%;
    box-sizing: border-box;
    background: var(--bg-canvas);
    color: var(--text-primary);
    border: 1px solid var(--border);
    border-radius: 3px;
    padding: 6px 8px;
    font: inherit;
    resize: vertical;
  }
  .preview {
    font-family: ui-monospace, "Cascadia Mono", Menlo, Consolas, monospace;
    font-size: 11px;
    color: var(--text-secondary);
  }
  .check {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 10px;
    font-size: 12px;
    color: var(--text-primary);
  }
  .privacy {
    margin: 10px 0 0;
    font-size: 11px;
    line-height: 1.5;
    color: var(--text-secondary);
  }
  .actions {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-top: 14px;
  }
  button {
    padding: 5px 12px;
    background: var(--bg-canvas);
    border: 1px solid var(--border);
    color: var(--text-primary);
    border-radius: 3px;
    cursor: pointer;
    font: inherit;
  }
  button:disabled {
    opacity: 0.55;
    cursor: default;
  }
  .discard {
    margin-left: auto;
    color: var(--text-secondary);
  }
</style>
