$ErrorActionPreference = 'Stop'

# Generated by scripts/gen-packaging.mjs — do not hand-edit the version or
# the checksum. Regenerate against the published release instead; a stale
# checksum here fails the install and reads like a corrupted download.
$packageArgs = @{
  packageName    = 'freally-sourcerer'
  fileType       = 'exe'
  url64bit       = 'https://github.com/MikesRuthless12/freally-sourcerer/releases/download/v0.23.2/Freally.Sourcerer_0.23.2_x64-setup.exe'
  checksum64     = 'DFEC5077934AE87F02C247399321F89B668016FC9404E0C9202D80E943E7D3E7'
  checksumType64 = 'sha256'
  # Tauri's NSIS installer takes NSIS's own silent switch.
  silentArgs     = '/S'
  validExitCodes = @(0)
}

Install-ChocolateyPackage @packageArgs
